### ISSUE TITLE
user friendly guidance

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#10]
### Value Statement
As a user I want to be guided through the usage of the advent calendar and I want to know about the prescription of the advent calendar.

### Description
Hints and self explaining navigation should make use of app easy and user friendly

### Acceptance Criteria
- [x]  the user finds familiar navigation concepts
- [x]  can get back to website at any time
- [x] can cancel all his/her actions

### Complexity
s/m

### Tasks
- [x] create on every side a go back arrow 
- [x]  join a href link to the logo which leads back to the main website
- [x] give the images alt tags
