### ISSUE TITLE
Cancel without finishing quiz

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#11]
### Value Statement
As a user I want to be warned if I leave the app without having solved the quiz or sent the email.

### Description
The users leaves the app without taking part in the lottery. 

### Acceptance Criteria
- [ ]  Ask if he/she wants to leave without any action.

### Complexity
M

### Tasks
- [ ] create a warning maybe a modal or just a message
- [ ] the warning should show when leaving the app 
- [ ] without having clicked an answer
- [ ] without having sent the email
