### ISSUE TITLE
Frontside -- day handling

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#12]
### Value Statement
As a user I want to make sure I am clicking the right date. Should be easy.

### Description
The clickable door corresponds to the actual day.

### Complexity
M

### Tasks
- [ ] only the door corresponding to the actual day is clickable
- [ ] the wrong doors are not clickable
- [x] combine the right door with day, question/answers and the lottery gift of that date
