### ISSUE TITLE
Header + Router

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#13]
### Value Statement
As a user I want to see on which side I am.

### Description
Header with logo and navigation

### Acceptance Criteria
- [ ]  user should see the header at any time
- [ ]  
- [ ]

### Complexity
s

### Tasks
- [x] create a header
- [x] add the logo
- [x] add link back to main website
- [x] attach that with a router
