### ISSUE TITLE
The basic form for the second page

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#14]
### Value Statement
As a user I want to 

### Acceptance Criteria
- [ ]  
- [ ]  
- [ ]

### Complexity
s

### Tasks
- [ ] create the look of the second page
- [ ] create the fields for the quiz
- [ ] and the items
- [ ] and the name, email input
- [ ] make some buttons
