### ISSUE TITLE
API

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#6]
### Value Statement
As a user I want to get new questions and want to have easy handling of the app.

### Description
API with quiz questions and answers, perhaps add the give aways or create a new API

### Acceptance Criteria
- [ ]  
- [ ]  
- [ ]

### Complexity
S

### Tasks
- [ ] create 1 or 2 API with some examples for testing
- [ ] complete the API with questions
- [ ] test the API
