### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#7]
### Value Statement
As a user I don't want to crash the app and get stuck somewhere.

### Description
Every user action in the app should be combined with error handling if possible or necessary

### Acceptance Criteria
- [ ]  user clicks on the advents calendar door
- [ ]  user reads question and click the right or wrong answer
- [ ] user types the email into email field 
- [ ] user clicks on 'sent' or cancel button

### Complexity
S

### Tasks
- [ ] create error message advents calendar door
- [ ] create error message right or wrong answer
- [ ] create error message email input field
- [ ] create error message 'sent' or cancel button
