### ISSUE TITLE
Quiz - End

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#8]
### Value Statement
As a user I want to have an easy way to send my email to take part in the lottery.

### Description
The user solves the lottery, clicks the right answer. Now he/she can send an email to the radio.

### Acceptance Criteria
- [ ] the user clicks the right answer, now he/she can send an email to take part in the lottery of the above signed gifts of the day

### Complexity
M

### Tasks
- [ ] create a function the watches over the click of the right answer
- [ ] this click opens an email form in which the email address, the right answer and the lottery win is shown. 
- [ ] make a button "Send Email"
- [ ] make a button "Cancel"
