### ISSUE TITLE
Quiz - Q and A handling

### ISSUE THREAD

**Issue by GabrieleGrimme** [GabrieleGrimme/Advent-Calendar#9]
### Value Statement
As a user I want to be helped going through the quiz and shown the right way 'through the djungle'.

### Description
The user can have another question or he/she can clear the radio buttons for a new start if wrong answer is given.

### Acceptance Criteria
- [ ]  the user clicks a radio button
- [ ]  the user can click the 3 wrong and only one right answer

### Complexity
M

### Tasks
- [ ]  the user clicks the wrong answer --> give him/her the hint "Wrong answer"
- [ ] add 2 buttons "clear" and "new question"
- [ ] make functions to make 'clear' and 'new question' -  button work
